title: Ung Vetenskapssports Matematiker
email: uvs-matematiker@ungvetenskapssport.se
description: >- 

baseurl: ""
url: "https://matematik.ungvetenskapssport.se/"
permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown
